name: Generate index.html

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate index.html
        run: python generate_index.py

      - name: Commit changes
        run: |
          git config --global user.name '0xUN7H1NK4BLE'
          git config --global user.email 'anishji0306@gmail.com'
          git add index.html
          git commit -m 'chore: auto-generate index.html [skip ci]' || echo "No changes to commit"

      - name: Pull latest changes
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Debug: Show git remote
        run: git remote -v

      - name: Debug: Show last commit author
        run: git log -1 --pretty=full

      - name: Push changes
        run: |
          git push https://${{ secrets.GH_PAT }}@github.com/0xUN7H1NK4BLE/photos.git HEAD:main  